name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a Ubuntu runner for deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout your code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Match the Python version with Azure App Service runtime

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-app-service-name>  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Azure publish profile from GitHub secrets
        package: .  # The package to deploy (current directory)
